# Generated by Django 3.0.2 on 2020-01-04 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
    ]
