# Generated by Django 3.0.2 on 2020-01-04 00:23

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='city name', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='location', max_length=63),
        ),
    ]
