# Generated by Django 3.0.2 on 2020-01-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200103_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default='address 1', max_length=255),
        ),
    ]
