# Generated by Django 3.0.2 on 2020-01-04 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='address',
            new_name='street_address',
        ),
    ]
