# Generated by Django 3.0.2 on 2020-01-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200103_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='city name'),
        ),
    ]
