# Generated by Django 3.0.2 on 2020-01-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_event_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
    ]
