# Generated by Django 3.0.2 on 2020-01-07 20:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0015_participants'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='participants',
            new_name='Participant',
        ),
    ]
