# Generated by Django 3.0.2 on 2020-01-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20200108_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(null=True, verbose_name='event date time'),
        ),
    ]
